# Generated by Django 4.0.4 on 2022-04-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'Feature'},
        ),
    ]
